interactions:
- request:
    body: "<?xml version='1.0' encoding='utf-8'?>\n<soap-env:Envelope xmlns:soap-env=\"\
      http://schemas.xmlsoap.org/soap/envelope/\"><soap-env:Body><ns0:registraOrden\
      \ xmlns:ns0=\"http://h2h.integration.spei.enlacefi.lgec.com/\"><ordenPago><claveRastreo>CR1536782279</claveRastreo><conceptoPago>concepto</conceptoPago><cuentaBeneficiario>846180000400000001</cuentaBeneficiario><empresa>TAMIZI</empresa><firma>y9c4tyd0XH0gCG21x1TNq7P4BR1VoxvV3IffeZCv8jiWK/uGbKWSequLsvS4O+kZOlJEBIoSRsTL1iHUEtgGbfL7joJeHE3hHFgBRX7sUQiNcGda2oWFNPjU1iLkPddJO4Ch7qvBzVm7HiyQEt9qkTBGa4aJFcO7J/vgC99AuiM=</firma><institucionContraparte>846</institucionContraparte><institucionOperante>90646</institucionOperante><medioEntrega>3</medioEntrega><monto>1234</monto><nombreBeneficiario>asdfghjkl\xF1\
      asdfghjkl\xF1asdfghjkl\xF1asdfghjkl\xF1</nombreBeneficiario><prioridad>1</prioridad><referenciaNumerica>1892415</referenciaNumerica><rfcCurpBeneficiario>ND</rfcCurpBeneficiario><tipoCuentaBeneficiario>40</tipoCuentaBeneficiario><tipoPago>1</tipoPago><topologia>T</topologia></ordenPago></ns0:registraOrden></soap-env:Body></soap-env:Envelope>"
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      Content-Length: ['1086']
      Content-Type: [text/xml; charset=utf-8]
      Cookie: [JSESSIONID=3kzPXemiMm6pWFDQeWldVFStOT3cWZd2Bfno4GOI4mQTWxK2zCCL!-221951421]
      SOAPAction: ['""']
      User-Agent: [Zeep/3.1.0 (www.python-zeep.org)]
    method: POST
    uri: https://demo.stpmex.com:7024/speidemo/webservices/SpeiActualizaServices
  response:
    body: {string: '<?xml version=''1.0'' encoding=''UTF-8''?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns0:registraOrdenResponse
        xmlns:ns0="http://h2h.integration.spei.enlacefi.lgec.com/"><return><descripcionError>JTA
        transaction unexpectedly rolled back (maybe due to a timeout); nested exception
        is weblogic.transaction.RollbackException: Unexpected exception in beforeCompletion:
        sync=org.hibernate.transaction.synchronization.HibernateSynchronizationImpl@93c1fd9

        org.hibernate.exception.DataException: Could not execute JDBC batch update</descripcionError><id>0</id></return></ns0:registraOrdenResponse></S:Body></S:Envelope>'}
    headers:
      Cache-Control: ['no-cache, no-store, must-revalidate, pre-check=0, post-check=0,
          max-age=0, s-maxage=0']
      Content-Type: [text/xml; charset=utf-8]
      Date: ['Wed, 12 Sep 2018 19:59:23 GMT']
      Expires: ['0']
      Pragma: [no-cache]
      Strict-Transport-Security: [max-age=31536000; includeSubdomains]
      X-Frame-Options: [DENY]
    status: {code: 200, message: OK}
version: 1
